version: 2

sources:
- name: fda_animals_raw
  schema: raw
  tables:
    - name: raw_payload
      identifier: raw_payload
      loaded_at_field: _created_at
      freshness:
        warn_after: {
          count: 90,
          period: day
        }
        error_after: {
          count: 100,
          period: day
        }