#Extra configs, tests, docs will be set up here

version: 2

models:
  - name: dim_listings_cleansed
    description: Table with proper formatting and data cleansing.
    columns:

      - name: listing_id
        description: Unique ID for listings.
        tests:
        - not_null
        - unique

      - name: host_id
        description: Unique ID for hosts.
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id

      - name: room_type
        description: Type of apartment
        tests:
          - accepted_values:
              values: [
                'Shared room',
                'Hotel room',
                'Private room',
                'Entire home/apt'
              ]
      
      - name: minimum_nights
        tests:
          - positive_value # a custom generic test

  - name: dim_hosts_cleansed
    columns:

      - name: is_superhost
        tests:
          - accepted_values:
              values: [
                't', 'f'
              ]